
- name: create swap file
  command: dd if=/dev/zero of={{ swap_file_path }} bs=1024 count={{ swap_file_size_kb }}k
           creates="{{ swap_file_path }}"
  tags: swap.file.create

- name: change swap file permissions
  file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600
  tags: swap.file.permissions

- name: check swap file type
  command: file {{ swap_file_path }}
  register: swapfile
  tags: swap.file.mkswap

- name: make swap file
  command: "mkswap {{ swap_file_path }}"
  when: swapfile.stdout.find('swap file') == -1
  tags: swap.file.mkswap

- name: write swap entry in fstab
  mount: name=none
         src={{ swap_file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  tags: swap.fstab

- name: mount swap
  command: "swapon {{ swap_file_path }}"
  when: ansible_swaptotal_mb < 1
  tags: swap.file.swapon
